-- Migration: add article_summaries table for the 3-bullet TL;DR feature.
-- Run via phpMyAdmin -> SQL tab against the lt1ih6uyy2z6_news database.
--
-- A 3-bullet TL;DR is generated by Claude Haiku from the extracted article
-- body (a separate, isolated pass after body extraction in
-- jobs/classify_pending.py) and cached here, keyed by article_id. Stored
-- apart from `articles`/`article_features` so the hot feed/ranking queries
-- stay lean. ON DELETE CASCADE means a summary is pruned automatically when
-- its article ages out (so saved/bookmarked articles keep their TL;DR for as
-- long as the article row survives the nightly retention prune).
--
-- LOAD-BEARING NOTE (BUG-007 / BUG-025 class on the cron write path):
-- jobs/classify_pending.py INSERTs into this table every tick once deployed.
-- It probes for the table's existence once per run and degrades to "no
-- summaries" if absent, so a missing migration will NOT freeze classification
-- the way the geo columns did (BUG-025) -- but apply this promptly anyway so
-- the feature actually produces summaries.
--
-- Fresh installs get this table from schema.sql.

CREATE TABLE IF NOT EXISTS article_summaries (
  article_id   BIGINT UNSIGNED NOT NULL,
  bullets_json TEXT NOT NULL,
  model        VARCHAR(64) NOT NULL DEFAULT '',
  generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (article_id),
  KEY idx_summaries_generated (generated_at),
  CONSTRAINT fk_summaries_article FOREIGN KEY (article_id) REFERENCES articles (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
